CREATE TABLE calculation
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT users_pkey PRIMARY KEY,
    number_1   VARCHAR(256) NOT NULL,
    notation_1 int  NOT NULL,
    number_2   VARCHAR(256) NOT NULL,
    notation_2 int  NOT NULL,
    operation  VARCHAR(10)  NOT NULL,
    date       VARCHAR(20)  NOT NULL,
    time       VARCHAR(20)  NOT NULL,
    result     VARCHAR(256) NOT NULL
);